# Generated by Django 4.2.20 on 2025-06-29 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0008_remove_publicacion_imagen_publicacion_archivo_media'),
        ('inicio', '0003_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicacion.publicacion'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('like', 'Like'), ('comentario', 'Comentario'), ('reporte', 'Reporte'), ('eliminado', 'Eliminado')], max_length=20),
        ),
    ]
