# Generated by Django 4.2.20 on 2025-07-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_notificacion_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medalla',
            name='imagen',
            field=models.CharField(max_length=200),
        ),
    ]
